package ahtbpoems

// Taken from http://www.bevrowe.info/Internet/Queneau/Queneau.html
var queneau_french = [10][14]string{
	{ // 1
		"Le roi de la pampa retourne sa chemise",
		"pour la mettre à sécher aux cornes des taureaux",
		"le cornédbîf  en boîte empeste la remise",
		"et fermentent de même et les cuirs et les peaux",
		"Je me souviens encor de cette heure exeuquise ",
		"les gauchos dans la plaine agitaient leurs drapeaux",
		"nous avions aussi froid que nus sur la banquise",
		"lorsque pour nous distraire y plantions nos tréteaux",
		"Du pôle à Rosario fait une belle trotte",
		"aventures on eut qui s'y pique s'y frotte",
		"lorsqu' on boit du maté l'on devient argentin",
		"L'Amérique du Sud séduit les équivoques ",
		"exaltent l'espagnol les oreilles baroques",
		"si la cloche se tait et son terlintintin",
	},
	{ // 2
		"Le cheval Parthénon s'énerve sur sa frise",
		"depuis que le lord Elgin négligea ses naseaux",
		"le Turc de ce temps-là pataugeait dans sa crise",
		"il chantait tout de même oui mais il chantait faux",
		"Le cheval Parthénon frissonnait sous la bise",
		"du climat londonien où s'ébattent les beaux",
		"il grelottait le pauvre au bords de la Tamise",
		"quand les grêlons fin mars mitraillent les bateaux",
		"La Grèce de Platon à coup sûr  n'est point sotte",
		"on comptait les esprits acérés à la hotte",
		"lorsque Socrate mort passait pour un lutin",
		"Sa sculpture est illustre et dans le fond des coques ",
		"on transporte et le marbre et débris et défroques",
		"si l'Europe le veut l'Europe ou son destin ",
	},
	{ // 3
		"Le vieux marin breton de tabac prit sa prise",
		"pour du fin  fond du nez exciter les arceaux",
		"sur l'antique bahut il choisit sa cerise",
		"il n'avait droit qu'à une et le jour des Rameaux",
		"Souvenez-vous amis de ces îles de Frise",
		"où venaient par milliers s'échouer les harenceaux",
		"nous regrettions un peu ce tas de marchandise",
		"lorsqu'on voyait au loin flamber les arbrisseaux",
		"On sèche le poisson dorade ou molve lotte",
		"on sale le requin on fume à l'échalotte",
		"lorsqu'on revient au port en essuyant un grain",
		"Enfin on vend le tout homards et salicoques",
		"on s'excuse il n'y a ni baleines ni phoques",
		"le mammifère est roi nous sommes son cousin",
	},
	{ // 4
		"C'était à cinq o'clock qu'il sortait la marquise",
		"pour consommer un thé puis des petits gâteaux",
		"le chauffeur indigène attendait dans la brise",
		"elle soufflait bien fort par dessus les côteaux",
		"On était bien surpris par cette plaine grise",
		"quand se carbonisait la fureur des châteaux",
		"un audacieux baron empoche toute accise",
		"lorsque vient le pompier avec ses grandes eaux",
		"Du Gange au Malabar le lord anglais zozotte",
		"comme à Chandernagor le manant sent la crotte",
		"le colonel s'éponge un blason dans la main",
		"Ne fallait pas si loin agiter ses breloques",
		"les Indes ont assez sans ça de pendeloques",
		"l'écu de vair ou d'or ne dure qu'un matin",
	},
	{ // 5
		"Du jeune avantageux la nymphe était éprise",
		"snob un peu sur les bords des bords fondamentaux",
		"une toge il portait qui n'était pas de mise",
		"des narcisses on cueille ou bien on est des veaux",
		"Quand on prend des photos de cette tour de Pise",
		"d'où Galilée jadis jeta ses petits pots",
		"d'une étrusque inscription la pierre était incise",
		"les Grecs et les Romains en vain cherchent leurs mots",
		"L'esprit souffle et resouffle au-dessus de la botte",
		"le touriste à Florence ignoble charibotte",
		"l'autocar écrabouille un peu d'esprit latin",
		"Les rapports transalpins sont-ils biunivoques?",
		"les banquiers d'Avignon changent-ils les baïoques?",
		"le Beaune et le Chianti sont-ils le même vin?",
	},
	{ // 6
		"Il se penche il voudrait attraper sa valise",
		"que convoitait c'est sûr une horde d'escrocs",
		"il se penche et alors à sa grande surprise",
		"il ne trouve aussi sec qu'un sac de vieux fayots",
		"Il déplore il déplore une telle mainmise",
		"qui se plaît à flouer de pauvres provinciaux ",
		"aller à la grand  ville est bien une entreprise",
		"elle effraie le Berry comme les Morvandiaux",
		"Devant la boue urbaine on retrousse sa cotte",
		"on gifle le marmot qui plonge sa menotte",
		"lorsqu'il voit la gadoue il cherche le purin",
		"On regrette à la fin les agrestes bicoques",
		"on mettait sans façon ses plus infectes loques",
		"mais on n'aurait pas vu le métropolitain",
	},
	{ // 7
		"Quand l'un avecque  l'autre aussitôt sympathise",
		"se faire il pourrait bien que ce soit des jumeaux",
		"la découverte alors voilà qui traumatise",
		"on espère toujours être de vrais normaux",
		"Et pourtant c'était lui le frère de feintise",
		"qui clochard devenant jetait ses oripeaux",
		"un frère même bas est la part indécise",
		"que les parents féconds offrent aux purs berceaux",
		"Le généalogiste observe leur bouillotte",
		"gratter le parchemin deviendra sa marotte",
		"il voudra retrouver le germe adultérin",
		"Frère je te comprends si parfois tu débloques",
		"frère je t'absoudrai si tu m'emberlucoques",
		"la gémellité vraie accuse son destin",
	},
	{ // 8
		"Lorsqu'un jour exalté l'aède prosaïse",
		"pour déplaire au profane aussi bien qu'aux idiots",
		"la critique lucide aperçoit ce qu'il vise",
		"il donne à la tribu des cris aux sens nouveaux",
		"L'un et l'autre a raison non la foule insoumise",
		"le vulgaire s'entête à vouloir des vers beaux",
		"l'un et l'autre ont raison non la foule imprécise",
		"à tous n'est pas donné d'aimer les chocs verbaux",
		"Le poète inspiré n'est point un polyglotte",
		"une langue suffit pour emplir sa cagnotte",
		"même s'il prend son sel au celte c'est son bien",
		"Barde que tu me plais toujours tu soliloques",
		"tu me stupéfies plus que tous les ventriloques",
		"le métromane à force incarne le devin",
	},
	{ // 9
		"Le marbre pour l'acide est une friandise",
		"d'aucuns par dessus tout prisent les escargots",
		"sur la place un forain de feu se gargarise",
		"qui sait si le requin boulotte les turbots",
		"Du voisin le Papou suçotte l'apophyse",
		"que n'a pas dévoré la horde des mulots?",
		"le gourmet en salade avale la  cytise",
		"l'enfant pur aux yeux bleus aime les berlingots?",
		"Le loup est amateur de coq et de cocotte",
		"le chat fait un festin de têtes de linotte",
		"le chemin vicinal se nourrit de crottin",
		"On a bu du pinard à toutes les époques",
		"grignoter des bretzels distrait bien des colloques",
		"mais rien ne vaut grillé le morceau de boudin",
	},
	{ // 10
		"Lorsque tout est fini lorsque l'on agonise",
		"lorsque le marbrier astique nos tombeaux",
		"des êtres indécis vous parlent sans franchise",
		"et tout vient signifier la fin des haricots",
		"On vous fait devenir une orde marchandise",
		"on prépare la route aux pensers sépulcraux",
		"de la mort on vous greffe une orde bâtardise",
		"la mite a grignoté tissus os et rideaux",
		"Le brave a beau crier ah cré nom saperlotte",
		"le lâche peut arguer de sa mine pâlotte",
		"les croque-morts sont là pour se mettre au turbin",
		"Cela considérant ô lecteur tu suffoques",
		"comptant tes abattis  lecteur tu te disloques",
		"toute chose pourtant doit avoir une fin",
	},
}

// Beverley Charles Rowe's English translation
// http://www.bevrowe.info/Internet/Queneau/Queneau.html
var queneau_english_rowe = [10][14]string{
	{ // 1
		"King Carlos turns his coat for better fees",
		"and sleeves are wrapped round horns of buffalo",
		"that tinned hornedbeef we stored smells more like cheese",
		"so stink the rotting skins from long ago",
		"I stille can call to mind those hours of eyse",
		"the gauchos waving flags bravissimo",
		"we chill like nudists put on ice to freeze",
		"to pass the time we stage a little show",
		"From Salta to the pole is quite a trot",
		"you mix with that you'll find you've had your lot",
		"drinking mate turns you Argentine",
		"Those Latin states spin like a weathercock",
		"baroque ears find that Spanish is a shock",
		"unless the bell is quiet and charltenteen",
	},
	{ // 2
		"The Parthenon horse looks nervous on the frieze",
		"since Elgin seems to think the nose de trop",
		"the Turk you see was deeply mired in sleaze",
		"the re in all his songs came out as doh",
		"The Parthenon horse is shivering in the biz",
		"benumbing London's dandies as they beau",
		"the flanks protected by chevaux de frise",
		"when March's hailstones batter the batteau",
		"Plato's Hellas surely wasn't sot",
		"with wits enough to fill a witenagemot",
		"as Socrates dies looking just Silene",
		"Its famous sculptures founder on a rock",
		"one carts off debris marble from the block",
		"if Europe or its destiny is keen",
	},
	{ // 3
		"The Breton tar lights up his duty-frees",
		"and sniffs the smoke that sets his nose aglow",
		"the chosen fruit is hued a bright cerise",
		"all during Lent one fruit's the ratio",
		"Remember friends those isles where live your Friese",
		"where shoals of herring boats now lie below",
		"that heap of goods occasions some unease",
		"when from afar we see the bushes grow",
		"We dry the fish sea bream or some burbot",
		"the shark is smoked on beds of bergamot",
		"while coming home we find the wind turned mean",
		"All's sold the prawns the lobsters our whole stock",
		"say sorry that no whales came back to dock",
		"so we are cousins now to king baleen",
	},
	{ // 4
		"At five o'clock he rests in his marquise",
		"consuming  tea and nibbling cream gateaux",
		"the native driver's waiting in the breeze",
		"across the hillocks comes a steady blow",
		"So plain a plain's not what one often sees",
		"as castles blaze and palaces burn low",
		"a daring baron pockets th' abkaris",
		"the fireman makes his mighty hoses flow",
		"Milord has lisped from Malibar to Swat",
		"at Chandrigar the peasant sniffs the pot",
		"shame gives the colonel's brow a greasy sheen",
		"Such ancestry is merely poppycock",
		"the Indies have enough without that schlock",
		"the shield of vair or or's but briefly seen",
	},
	{ // 5
		"The gorgeous youth helps Hestia's heart unfreeze",
		"he's cast out like a snobby Romeo",
		"he wore his toga like an old chemise",
		"you pluck narcissi or you're very slow",
		"Those snaps of Pisa's tower are bound to please",
		"where Galileo once took pots to throw",
		"a Tuscan scribed the stone with his imprese",
		"the Greeks and Romans read and thought 'what though?'",
		"A witty wind stops Ities speaking rot",
		"in Florence tourists see a deal of grot",
		"you can't quote Virgil in a limousine",
		"Those transalpine relations interlock?",
		"the bankers in Provence exchange baiock?",
		"both Beaune and Chianti flow from Hippocrene?",
	},
	{ // 6
		"He's well inclined to capture his valise",
		"enough to spur on any picaro",
		"he'd much to learn despite his four degrees",
		"there's naught as dry as sacks of haricot",
		"He hates he hates the work of sequestrees",
		"so keen to part poor bumpkins from their dough",
		"going up to visit town is quite a wheeze",
		"it frightens Berry and the Morvandiaux",
		"Faced with mud you'll turn up your culotte",
		"we'll smack the dibbing kiddie's little bot",
		"manure not slush besmirched his gabardine ",
		"You'll come to miss the peasant in his smock",
		"you start to travel looking like a brock",
		"at least the metro's one place where you've been",
	},
	{ // 7
		"When each of you with all his heart agrees",
		"being twinned is better far than  single-o",
		"it's finding out that's likely to displease",
		"we always hope to keep ourselves so-so",
		"And thus it was a sib steeped in sottise",
		"who beggared gave his rags the old heave-ho",
		"e'en low bro's lead to diaporeses",
		"when parents sanctify the babygro",
		"The genealogist finds every blot",
		"to cease from scratching parchment he cannot",
		"he'd really like to root out the cuckquean",
		"Oh brother even when you groan I grok",
		"I quite forgive you when you run amok",
		"true twinship blames whatever's in the gene",
	},
	{ // 8
		"So now the bard spurns iambs and trochees",
		"to aggravate the layman and the shmo",
		"he writes reviews that read like journalese",
		"which freshens up the tribal rumbelow",
		"Just one was right and not those SOBs",
		"the mob demands that verse be comme il faut",
		"both are right not that vague congeries",
		"most people like to read the words they know",
		"Th' inspired poet isn't polyglot",
		"in his brain one tongue is all he's got",
		"e'en stol'n from th' celts his muse remains his queen",
		"O bard your solo readings make me mock",
		"I nominate you as a gapingstock",
		"the metromaniacs outdo Racine",
	},
	{ // 9
		"The conjuror eats watches pens or keys",
		"any diner chooses escargots",
		"eat fire your mouth will taste like antifreeze",
		"who knows if sharks will feast on bummalo",
		"The Papuan sucks his friend's apophyses",
		"those greedy mice leave nothing for the crow",
		"mixing broom with chives shows expertise ",
		"but offering kids a sweetie that's no-no",
		"The wolf adores the cock and the cocotte",
		"a cat will munch a bird but spurn shallot",
		"the local road laps up leaked gasoline",
		"We've all downed plonk from Calais to Bangkok",
		"at meetings nibble nuts and watch the clock",
		"but best is grilled black pudding with sardine",
	},
	{ // 10
		"One's left with only sorrow and disease",
		"the undertakers peer and say Oho",
		"the timid mutter into their goatees",
		"you hear your spouse pay off the medico",
		"You get like dirty goods on busy quays",
		"your mind turns more and more to gloom and woe",
		"for death casts piles of shit on pedigrees",
		"with moth and rust we settle all we owe",
		"The brave man cries I do not care a jot",
		"the coward mutters Why was I begot?",
		"the masons give your tomb a final clean ",
		"Oh reader thinking thus your heart will lock",
		"you cannot number off  each ploch and pock",
		"clear from the start the ending is foreseen",
	},
	/*
		{ // 11
			"The model boy loves shirts designed by Guise",
			"you'll see him with Laurent inside Hello!",
			"the girls all bare their arms and tits and knees",
			"in silk wool cotton denim calico",
			"The clothes they hardly wear are meant to tease",
			"with necklines basso hems altissimo",
			"yet nothing's more vieux jeu than dungarees",
			"round Venice girls just have to wear Liu-Jo",
			"Can supermodels fly from spot to spot?",
			"it's not the lights that make a model hot",
			"create a sexy look with clothes from Preen",
			"That isn't talcum powder on her frock",
			"take care with stockings made by Aristoc",
			"did Philip fret while Hartnell dressed the queen?",
		},
		{ // 12
			"The pessimist says phones kill bumblebees",
			"all's gloom and doom from film and radio",
			"if oceans rise say goodbye to Belize",
			"if glaciers melt it's bad for Eskimo",
			"There'll be a billion sweating refugees",
			"when Norfolk drowns we'll just say Cheerio",
			"and pinch more land from aborigines",
			"did Voltaire think of gardens all aflow?",
			"We can't read Blake if tygers are all shot",
			"when flowers die forget forget-me-not",
			"now trees are everbrown not evergreen",
			"We've spurned the tick and some can't hear the tock",
			"we're moving wealth around from sock to sock",
			"no Kent or Scillies nor much in between",
		},
	*/
}

// Stanley Chapman's English translation
// https://github.com/possibly/a-hundred-thousand-billion-poems-explorer
// Last 6 lines indented like the original poem
var queneau_english_chapman = [10][14]string{
	{ // 1
		"Don Pedro from his shirt has washed the fleas",
		"The bull's horns ought to dry it like a bone",
		"Old corned-beef's rusty armour spreads disease",
		"That suede ferments is not at all well known",
		"To one sweet hour of bliss my memory clings",
		"Signalling gauchos very rarely shave",
		"An icicle of frozen marrow pings",
		"As sleeping-bags the silent landscape pave",
		"     Staunch pilgrims longest journeys can't depress",
		"     What things we did we went the whole darned hog",
		"     And played their mountain croquet jungle chess",
		"     Southern baroque's seductive dialogue",
		"     Suits lisping Spanish tongues for whom say some",
		"     The bell tolls fee-less fi-less fo-less fum",
	},

	{ // 2
		"The wild horse champs the Parthenon's top frieze",
		"Since Elgin left his nostrils in the stone",
		"The Turks said just take anything you please",
		"And loudly sang off-key without a tone",
		"O Parthenon you hold the charger's strings",
		"The North Wind Bites into his architrave",
		"Th'outrageous Thames a troubled arrow slings",
		"To break a rule Britannia's might might waive",
		"     Platonic Greece was not so talentless",
		"     A piercint wit would sprightliest horses flog",
		"     Socrates watched his hemlock effervesce",
		"     Their sculptors did our best our hulks they clog",
		"     With marble souvenirs then fill a slum",
		"     For Europe's glory whjiole Fate's harpies strum",
	},

	{ // 3
		"At snuff no Cornish sailorman would sneeze",
		"His nasal ecstasy beats best Cologne",
		"Upon his old oak chest he cuts his cheese",
		"With cherry-pips his cottage floor is sown",
		"The Frisian Isles my friends are cherished things",
		"Whose ocean still-born herrings madly brave",
		"Such merchandise a melancholy brings",
		"For burning bushes never fish forgave",
		"     When dried the terrapin can naught express",
		"     Shallots and sharks' fins face the smould'ring log",
		"     While homeward thirsts to each quenched glass say yes",
		"     Lobsters for sale must be our apologue",
		"     On fish-slab whale nor seal has never swum",
		"     They're kings we're mammal-cousins hi ho hum",
	},

	{ // 4
		"At five precisely out went La Marquise",
		"For tea cucumber sandwiches a scone",
		"Her native chauffeur waited in the breeze",
		"Which neither time nor tide can long postpone",
		"How it surprised us pale grey underlings",
		"When flame a form to wrath ancestral gave",
		"A darling baron pockets precious Mings",
		"Till firemen come with hose-piped tidal wave",
		"     The fasting fakir doesn't smell the less",
		"     In Indian summers Englishmen drink grog",
		"     The colonel's still escutcheoned in undress",
		"     No need to cart such treasures from the fog",
		"     The Taj Mahal has trinkets spice and gum",
		"     And lessors' dates have all too short a sum",
	},

	{ // 5
		"From playboy Chance the nymph no longer flees",
		"Through snobbish growing round her hemline zone",
		"His toga rumpled high above his knees",
		"One gathers rosebuds or grows old alone",
		"Old Galileo's Pisan offerings",
		"Were pots graffiti'd over by a slave",
		"The leaning linguist cameramaniac sings",
		"Etruscan words which Greece and Rome engrave",
		"     Emboggled minds may puff and blow and guess",
		"     With gravity at gravity's great cog",
		"     On wheels the tourist follows his hostess",
		"     With breaking voice across the Alps they slog",
		"     Do bank clerks rule their abacus by thumb?",
		"     In cognac brandy is Bacardi rum?",
	},

	{ // 6
		"He bent right down to pick up his valise",
		"That hordes of crooks felt they'd more right to own",
		"He bent right down and well what did he seize",
		"The thumb- and finger-prints of Al Capone",
		"Oh how oh how he hates such pilferings",
		"Filching the lolly country thrift helped save",
		"He's gone to London how the echo rings",
		"Through homestead hillside woodland rock and cave",
		"     The peasant's skirts on rainy days she'd tress",
		"     And starve the snivelling baby like a dog",
		"     Watching manure and compost coalesce",
		"     One misses cricket hearth and croaking frog",
		"     Where no one bothered how one warmed one's bum",
		"     Yet from the City's pie pulled not one plum",
	},

	{ // 7
		"When one with t'other straightaway agrees",
		"The answer is they could be twins full-grown",
		"Replies like this the dumbstruck brain may tease",
		"Normal one aims to be and share the throne",
		"And yet 'twas he the beggar Fate just flings",
		"Rejecting ermine to become a knave",
		"The fertile mmother changeling drops like kings",
		"In purest cradles tha's how they behave",
		"     The genealogist with field and fess",
		"     With quill white-collared through his life will jog",
		"     To prove mamma an adult with a tress",
		"     But I can understand you Brogher Gog",
		"     And let you off from your opinions glum",
		"     A wise loaf always knows its humblest crumb",
	},

	{ // 8
		"Prose took the minstrel's verse without a squeeze",
		"His exaltation shocked both youth and crone",
		"The understanding critic firstly sees",
		"'Ere meanings new to ancient tribes are thrown",
		"They both are right not untamed mutterings",
		"That metred rhyme alone can souls enslave",
		"They both are right not unformed smatterings",
		"That every verbal shock aims to deprave",
		"     Poetic licence needs no strain or stress",
		"     One tongue will do to keep the verse agog",
		"     From cool Parnassus down to wild Loch Ness",
		"     Bard I adore your endless monologue",
		"     Ventriloquists be blowed you strike me dumb",
		"     Soliloquies predict great things old chum",
	},

	{ // 9
		"The acid tongue with gourmet's experties",
		"Licks round carved marble chops on snails full-blown",
		"The showman gargles fire and sword with ease",
		"While sharks to let's say potted shrimps are prone",
		"The roundabout eats profits made on swings",
		"Nought can the mouse's timid nibbling stave",
		"In salads all chew grubs before they've wings",
		"The nicest kids for strickiest toffees crave",
		"     The wolf devours both sheep and shepherdess",
		"     A bird-brain banquet melts bold Mistress Mog",
		"     The country land just thrives on farmyard mess",
		"     Whiskey will always wake an Irish bog",
		"     Though bretzels take the dols from board-room drum",
		"     Fried grilled black pudding's still whe world's best yum",
	},

	{ // 10
		"The marble tomb gapes wide with jangling keys",
		"When masons clutch the breath we hold on loan",
		"Forms shadowy with indecision wheeze",
		"And empty cages show lif'e bird has flown",
		"It's one of many horrid happenings",
		"With sombre thoughts they grimly line the nave",
		"Proud death quite il-le-gi-ti-mate-ly stings",
		"Victorious worms grind all into the grave",
		"     It's no good rich men crying Heaven Bless",
		"     Or grinning like a pale-faced golliwog",
		"     Poor Yorick comes to bury not address",
		"     We'll suffocate before the epilogue",
		"     Poor reader smile before your lips go numb",
		"     The best of all things to an end must come",
	},
}
